version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: audit-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: audit_tool
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Supabase local development
  # Uncomment if you want to use Supabase locally instead of the cloud
  # supabase-db:
  #   image: supabase/postgres:15.1.0.55
  #   container_name: supabase-db
  #   environment:
  #     POSTGRES_PASSWORD: your-super-secret-password
  #   ports:
  #     - "54322:5432"
  #   volumes:
  #     - supabase_db_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  # supabase_db_data: